/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import clasesFuncionales.Cliente;
import clasesFuncionales.ClienteEntidad;
import clasesFuncionales.ClientePersona;
import clasesFuncionales.Fecha;

/**
 * Ventana de Jframe que funciona como detalles de la operacion realizada segun la operacion hecha
 * @author Martin
 */
public class Detalles_Operacion extends javax.swing.JFrame {
    /**
     * Instancia del cliente actual
    */
    private Cliente cliente;
    /**
     * Creates new form Detalles_Operacion
     * @param Operacion Valor que define la operacion a realizar
     * @param monto Valor que indica el monto que se pago/deposito en la operacion
     * @param Detalles String de pequeña descripcion de la operacion que se realizo
     */
    public Detalles_Operacion(int Operacion, long monto,String Detalles) {
        initComponents();
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        Fecha fecha = new Fecha(true);
        String Linea;
        switch (Operacion){
            case 1:
                Linea="Operacion: Deposito\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="NroCuenta: "+cliente.getNroCuenta()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Nombre: "+cliente.getNombre()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Fecha: "+fecha.toStringCorto(true)+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Monto: "+monto+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                break;
                
            case 2:
                Linea="Operacion: Transferencia\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="NroCuenta: "+cliente.getNroCuenta()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Nombre: "+cliente.getNombre()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Fecha: "+fecha.toStringCorto(true)+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Monto: "+monto+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Cuenta Destino: "+Detalles+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                
                break;
                
            case 3:
                Linea="Operacion: Pago Entidad\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="NroCuenta: "+cliente.getNroCuenta()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Nombre: "+cliente.getNombre()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Fecha: "+fecha.toStringCorto(true)+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Monto: "+monto+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Servicio Pagado: "+Detalles+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                
                break;
                
            case 4:
                Linea="Operacion: Pago Tarjeta\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="NroCuenta: "+cliente.getNroCuenta()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Nombre: "+cliente.getNombre()+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Fecha: "+fecha.toStringCorto(true)+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Monto: "+monto+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                Linea="Tarjeta Pagada: "+Detalles+"\n";
                Panel_Detalles.setText(Panel_Detalles.getText()+Linea);
                
                break;
                
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Panel_Detalles = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        BotonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 191, 168));

        jPanel1.setBackground(new java.awt.Color(114, 145, 147));

        Panel_Detalles.setEditable(false);
        Panel_Detalles.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(Panel_Detalles);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel1.setText("Recibo de operación");

        BotonCerrar.setBackground(new java.awt.Color(245, 205, 195));
        BotonCerrar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        BotonCerrar.setText("Cerrar");
        BotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1)
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(BotonCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonCerrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BotonCerrarActionPerformed

    /**
     * Metodo main de Detalles_Operacion
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalles_Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalles_Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalles_Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalles_Operacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JTextPane Panel_Detalles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
