/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;
import clasesFuncionales.*;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import static pkgfinal.VolverAtras.BotonVolver;

/**
 * Jframe principal del programa en donde el usuario eligue que operacion va a realizar y demas
 * @author lucas
 */
public class Interfaz_Pantalla_Principal extends javax.swing.JFrame implements VolverAtras{
    /**
     * Instancia de cliente a ser utilizada
     */
    protected Cliente cliente;
    /**
     * Instancia de la VEntana Interfaz_Pantalla_Principal para evitar duplicados
     */
    private static Interfaz_Pantalla_Principal instance;
    
    /**
     * Metodo que devuelve la instancia de la Pantalla_Principal para evitar duplicados
     * @return Devuelve la instancia de la pantalla principal
     */
    public static Interfaz_Pantalla_Principal getInstance() {
        return instance;
    }
    
    /**
     * Creates new form Pantalla_principal
     */
    public Interfaz_Pantalla_Principal() {
        instance=this;
        initComponents();
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA; 
        }
        
        //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        // Cancelar Pantalla completa
        setMaximizedBounds(getBounds());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Realizar_Pagos = new javax.swing.JToggleButton();
        Historial = new javax.swing.JButton();
        Obtener_Datos_Cuenta = new javax.swing.JButton();
        Transferencia = new javax.swing.JButton();
        Depositar = new javax.swing.JButton();
        Cerrar_Sesion = new javax.swing.JButton();
        BotonAyuda = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 102, 104));

        jPanel1.setBackground(new java.awt.Color(104, 145, 147));

        Realizar_Pagos.setBackground(new java.awt.Color(245, 205, 195));
        Realizar_Pagos.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Realizar_Pagos.setText("Realizar Pagos");
        Realizar_Pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Realizar_Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_PagosActionPerformed(evt);
            }
        });

        Historial.setBackground(new java.awt.Color(245, 205, 195));
        Historial.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Historial.setText("Historial de Transacciones");
        Historial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });

        Obtener_Datos_Cuenta.setBackground(new java.awt.Color(245, 205, 195));
        Obtener_Datos_Cuenta.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Obtener_Datos_Cuenta.setText("Ver Información");
        Obtener_Datos_Cuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Obtener_Datos_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Obtener_Datos_CuentaActionPerformed(evt);
            }
        });

        Transferencia.setBackground(new java.awt.Color(245, 205, 195));
        Transferencia.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Transferencia.setText("Transferencia");
        Transferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferenciaActionPerformed(evt);
            }
        });

        Depositar.setBackground(new java.awt.Color(245, 205, 195));
        Depositar.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Depositar.setText("Realizar Depósito");
        Depositar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Obtener_Datos_Cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Realizar_Pagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Depositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Transferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Obtener_Datos_Cuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Realizar_Pagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Historial)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Cerrar_Sesion.setBackground(new java.awt.Color(245, 205, 195));
        Cerrar_Sesion.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Cerrar_Sesion.setText("Cerrar sesión");
        Cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_SesionActionPerformed(evt);
            }
        });

        BotonAyuda.setBackground(new java.awt.Color(245, 205, 195));
        BotonAyuda.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        BotonAyuda.setText("Ayuda");
        BotonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Cerrar_Sesion))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(Cerrar_Sesion)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo que realiza el cierre de sesion para que otro usuario pueda usar el programa
     * @param evt 
     */
    private void Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_SesionActionPerformed
        Interfaz_Iniciar_Sesion cerrarSesion= new Interfaz_Iniciar_Sesion(); 
        cerrarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Cerrar_SesionActionPerformed
    /**
     * Metodo que abre la ventana para realizar transferencias
     * @param evt 
     */
    private void TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferenciaActionPerformed
       Interfaz_Transferencia ventana =new Interfaz_Transferencia();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransferenciaActionPerformed
    /**
     * Metodo que te abre la ventana para realizar pagos
     * @param evt 
     */
    private void Realizar_PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_PagosActionPerformed
        Interfaz_Realizar_Pagos  ventana =new Interfaz_Realizar_Pagos();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Realizar_PagosActionPerformed
    /**
     * Metodo que te abre la ventana para ver los datos del usuario
     * @param evt 
     */
    private void Obtener_Datos_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Obtener_Datos_CuentaActionPerformed
        Interfaz_DatosUsuario ventana =new Interfaz_DatosUsuario();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Obtener_Datos_CuentaActionPerformed
    /**
     * Metodo que te abre la ventana para realizar un deposito
     * @param evt 
     */
    private void DepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositarActionPerformed
        Interfaz_Realizar_Deposito ventana =new Interfaz_Realizar_Deposito();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DepositarActionPerformed
    /**
     * Metodo que te abre la ventana para ver el historial
     * @param evt 
     */
    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        Interfaz_Historial ventana =new Interfaz_Historial();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistorialActionPerformed
    /**
     * Metodo que te abre la ventana de ayuda con datos varios
     * @param evt 
     */
    private void BotonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaActionPerformed
        Interfaz_Ayuda ventana=new Interfaz_Ayuda();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAyudaActionPerformed

    /**
     * Metodo main de la Interfaz_Pantalla_Principal
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAyuda;
    private javax.swing.JButton Cerrar_Sesion;
    private javax.swing.JButton Depositar;
    private javax.swing.JButton Historial;
    private javax.swing.JButton Obtener_Datos_Cuenta;
    private javax.swing.JToggleButton Realizar_Pagos;
    private javax.swing.JButton Transferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}
}
