/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import Funciones.Funciones;
import clasesFuncionales.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static pkgfinal.VolverAtras.BotonVolver;

/**
 * Clase de Jframe en donde se realizan las transferencias entre clientes
 * @author lucas
 */
public class Interfaz_Transferencia extends javax.swing.JFrame implements VolverAtras {

    /**
     * Atributo que define el limite
     */
    private int limiteDeCi=7;
    /**
     * Instancia del cliente a utilizar
     */
    protected Cliente cliente;
    /**
     * instancia de la interfaz para que no se creen duplicado
     */
    protected static Interfaz_Transferencia instance;
    /**
     * Metodo que devuelve una instancia de la ventana para evitar duplicados
     * @return instancia de la interfaz_Transferencia
     */
    public static Interfaz_Transferencia getInstance() {
        return instance;
    }
    /**
     * Creates new form Transferencia
     */
    public Interfaz_Transferencia() {
        try {
            FondoPanel fondo = new FondoPanel();
            // Resto del código
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        initComponents();
        jLabel9.setVisible(false);
        instance = this;
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        add(BotonVolver);
        
        // Cambiar el color del botón usando RGB
       Color colorFondo = new Color(245, 203, 195); // para RGB
        BotonVolver.setBackground(colorFondo);
        BotonVolver.setForeground(Color.BLACK); // Cambiar el color del texto

        // Cambiar el tipo de letra del botón
        Font font = new Font("Nirmala UI", Font.PLAIN, 16); 
        BotonVolver.setFont(font);
        
        BotonVolver.setBounds(135, 390, 100, 30);
        BotonVolver.addActionListener(new ActionListener(){  
            public void actionPerformed(ActionEvent e){  
                Interfaz_Pantalla_Principal PantallaPrincipal = Interfaz_Pantalla_Principal.getInstance();
                PantallaPrincipal.setVisible(true);
                dispose();
                
            }  
        }); 
        
        
        
         //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        // Cancelar Pantalla completa
        setMaximizedBounds(getBounds());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BotonConfirmarTransferencia = new javax.swing.JButton();
        Ingresar_Nombre = new javax.swing.JTextField();
        IngresarNaturaleza = new javax.swing.JTextField();
        IngresarNROCuenta = new javax.swing.JTextField();
        IngresarNROCI = new javax.swing.JTextField();
        Ingresar_Monto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(94, 102, 104));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel10.setText("Transferencia entre cuentas bancarias");

        jPanel4.setBackground(new java.awt.Color(114, 145, 147));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel11.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel12.setText("Documento");

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel14.setText("Raz�n");

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel15.setText("Monto");

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel16.setText("Numero de Cuenta");

        BotonConfirmarTransferencia.setBackground(new java.awt.Color(240, 205, 195));
        BotonConfirmarTransferencia.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        BotonConfirmarTransferencia.setText("Confirmar");
        BotonConfirmarTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarTransferenciaActionPerformed(evt);
            }
        });

        Ingresar_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_NombreKeyTyped(evt);
            }
        });

        IngresarNaturaleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNaturalezaActionPerformed(evt);
            }
        });
        IngresarNaturaleza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNaturalezaKeyTyped(evt);
            }
        });

        IngresarNROCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNROCuentaKeyTyped(evt);
            }
        });

        IngresarNROCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNROCIKeyTyped(evt);
            }
        });

        Ingresar_Monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_MontoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Saldo Insuficiente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IngresarNROCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ingresar_Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresarNaturaleza)
                    .addComponent(IngresarNROCI)
                    .addComponent(Ingresar_Monto)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(BotonConfirmarTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IngresarNROCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(8, 8, 8)
                .addComponent(IngresarNaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(Ingresar_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonConfirmarTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(10, 10, 10)
                .addComponent(Ingresar_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarNROCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(46, 46, 46))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConfirmarTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarTransferenciaActionPerformed

        if (IngresarNROCI.getText().isEmpty() || IngresarNROCuenta.getText().isEmpty() || IngresarNaturaleza.getText().isEmpty() ||
            Ingresar_Nombre.getText().isEmpty()|| Ingresar_Monto.getText().isEmpty() ) {

            int camposVacios = 0;
            StringBuilder mensajeError = new StringBuilder("Error: Uno o más campos están vacíos en los siguientes campos:\n");

            if (IngresarNROCI.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Cedula\n");
            }
            if (IngresarNROCuenta.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Numero de Cuenta\n");
            }
            if (IngresarNaturaleza.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Naturaleza\n");
            }
            if (Ingresar_Nombre.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Nombre\n");
            }

            if (Ingresar_Monto.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Monto\n");
            }

            if (camposVacios > 0) {
                // Mostrar solo los campos que no están completos
                JOptionPane.showMessageDialog(this, mensajeError.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        if ((Integer.parseInt(IngresarNROCuenta.getText()))==cliente.getNroCuenta() ){
            JOptionPane.showMessageDialog(this, "Error, la cuenta destino no puede ser la misma con la que transfieres", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Long.parseLong(Ingresar_Monto.getText().trim()) > cliente.getFondos()){
            jLabel9.setVisible(true);
            return;
        }

        if (!Funciones.ExistenciaCuenta(IngresarNROCuenta.getText())){
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no esta en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Interfaz_Validacion confirmar = new Interfaz_Validacion(2);
        confirmar.setVisible(true);

    }//GEN-LAST:event_BotonConfirmarTransferenciaActionPerformed

    private void Ingresar_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_NombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();  // Rechaza la entrada que sea un número
        }
    }//GEN-LAST:event_Ingresar_NombreKeyTyped

    private void IngresarNaturalezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNaturalezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNaturalezaActionPerformed

    private void IngresarNaturalezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNaturalezaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();  // Rechaza la entrada que sea un número
        }
    }//GEN-LAST:event_IngresarNaturalezaKeyTyped

    private void IngresarNROCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNROCuentaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }
    }//GEN-LAST:event_IngresarNROCuentaKeyTyped

    private void IngresarNROCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNROCIKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }

        if (IngresarNROCI.getText().length() >= limiteDeCi ) {
            evt.consume(); // Rechaza la entrada si se alcanza la longitud máxima
        }
    }//GEN-LAST:event_IngresarNROCIKeyTyped

    private void Ingresar_MontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_MontoKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }
    }//GEN-LAST:event_Ingresar_MontoKeyTyped
    /**
     * Metodo que realiza las transferencias entre cuentas
     */
    public void Realizar_Transferencia(){
        int NroCuenta = Integer.parseInt(IngresarNROCuenta.getText().trim());
        int cuenta = Funciones.verificarExistenciaCuenta(NroCuenta, "src\\Documentos\\Usuarios\\Usuario");
        if (cuenta!=0){
            ClientePersona cliente2 = new ClientePersona();
            cliente2 = Funciones.leerClientePDesdeArchivo("src\\Documentos\\Usuarios\\Usuario"+cuenta+".txt" ,cuenta );
            
            Long monto = Long.parseLong(Ingresar_Monto.getText().trim());
            Long montoTotal = cliente2.getFondos()+monto;
           
            String LineaSobre1=String.format("Fondos: %-20d", montoTotal);
            
            /*
            Aumentamos los fondos a los que estamos transfiriendo el dinero
            */
            try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\Usuarios\\Usuario"+cuenta+".txt" , "rw")) {
                long posicion=0;
                int aux=1,lineaSob=12;        //En los archivos txt en la linea 11 esta el dato a sobreescribir
                String linea;
                while ((linea = file.readLine()) != null) {
                    if (aux==lineaSob) {
                        posicion=file.getFilePointer();
                        break;
                    }
                    aux++;
                }
                
                file.seek(posicion);
                file.writeBytes(LineaSobre1);
                file.writeBytes(System.lineSeparator());
                
            } catch (IOException e) {
                e.printStackTrace();
            }
            /*
            Disminuimos los fondos de la cuenta en la que estamos actualmente
            */
            montoTotal=cliente2.getFondos()-monto;
            String LineaSobre2=String.format("Fondos: %-20d", montoTotal); ;
            
            try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\Usuarios\\Usuario"+cliente.getArchivo()+".txt" , "rw")) {
                long posicion=0;
                int aux=1,lineaSob=12;        //En los archivos txt en la linea 11 esta el dato a sobreescribir
                String linea;
                while ((linea = file.readLine()) != null) {
                    if (aux==lineaSob) {
                        posicion=file.getFilePointer();
                        break;
                    }
                    aux++;
                }
                
                file.seek(posicion);
                file.writeBytes(LineaSobre2);
                file.writeBytes(System.lineSeparator());
                
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            cliente2.setFondos(montoTotal);
            Agregar_Transferencia();
            JOptionPane.showMessageDialog(this, "Deposito realizado con exito!!", "Transferencia Exitosa", JOptionPane.INFORMATION_MESSAGE);
            Interfaz_Pantalla_Principal principal = Interfaz_Pantalla_Principal.getInstance();
            principal.setVisible(true);
            Detalles_Operacion detalles = new Detalles_Operacion(2,monto,IngresarNROCuenta.getText());
            detalles.setVisible(true);
            dispose();
            
        }
    }
    /**
     * Metodo que agrega la transferencia al archivo de historial
     */
    public void Agregar_Transferencia(){
        String ubicacion_Archivos="src\\Documentos\\Historiales\\Historial";
        int iteracion=0;
        while (true){
            iteracion++;
            String Terminacion=iteracion+".txt";
            try(RandomAccessFile file = new RandomAccessFile(ubicacion_Archivos+Terminacion, "rw")){
                
                String linea=linea=file.readLine();
                
                Integer NroCuenta=Integer.parseInt(linea.substring("NroCuenta: ".length()).trim());

                if (NroCuenta.equals(cliente.getNroCuenta())){
                    
                    while ((linea=file.readLine())!=null);
                    LocalDate fechaHora = LocalDate.now();
                    String LineaSobre1=String.format("|%-10s|%-30s|%-20d|%-12s|\n", fechaHora.toString(),"Transferencia cuenta "+IngresarNROCuenta.getText() ,Long.parseLong(Ingresar_Monto.getText()),"Negativo");
                    file.writeBytes(LineaSobre1);
                    String LineaDos="|----------|------------------------------|--------------------|------------|\n";
                    file.writeBytes(LineaDos);
                    break;
                }
                
            } catch(Exception e){
                System.out.println("Error");
                break;
            }
        }
    }
    
    /**
     * Metodo main de la ventana Interfaz_Transferencia
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmarTransferencia;
    private javax.swing.JTextField IngresarNROCI;
    private javax.swing.JTextField IngresarNROCuenta;
    private javax.swing.JTextField IngresarNaturaleza;
    private javax.swing.JTextField Ingresar_Monto;
    private javax.swing.JTextField Ingresar_Nombre;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    
    
    class FondoPanel extends JPanel {
        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
