/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;
import javax.swing.JOptionPane;

//import paquetes
import Funciones.*;
import clasesFuncionales.*;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 * Ventana principal de inicio que es donde el usuario carga sus datos para poder iniciar sesion y comenzar el programa
 * @author lucas
 */
public class Interfaz_Iniciar_Sesion extends javax.swing.JFrame implements VolverAtras{
    
    FondoPanel fondo=new FondoPanel();
    
    
    static Interfaz_Iniciar_Sesion getInstance() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form Iniciar_Sesion
     */
    public Interfaz_Iniciar_Sesion() {
        
        initComponents();
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        
        setMaximizedBounds(getBounds());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IngresarNroCuenta = new javax.swing.JTextField();
        IngresarPinCuenta = new javax.swing.JPasswordField();
        Texto_Contrasenha = new javax.swing.JLabel();
        Verificar_Datos = new javax.swing.JButton();
        Cerrar_Programa_Iniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(94, 102, 104));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 102, 104));

        jPanel1.setBackground(new java.awt.Color(114, 145, 147));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel1.setText("Ingrese su número de cuenta");

        IngresarNroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNroCuentaActionPerformed(evt);
            }
        });

        IngresarPinCuenta.setToolTipText("");
        IngresarPinCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        IngresarPinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPinCuentaActionPerformed(evt);
            }
        });

        Texto_Contrasenha.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Texto_Contrasenha.setText("Ingrese su pin de Acceso");

        Verificar_Datos.setBackground(new java.awt.Color(250, 205, 195));
        Verificar_Datos.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Verificar_Datos.setText("Ingresar");
        Verificar_Datos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Verificar_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verificar_DatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(IngresarNroCuenta)
                    .addComponent(IngresarPinCuenta)
                    .addComponent(Texto_Contrasenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Verificar_Datos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Texto_Contrasenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarPinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Verificar_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        Cerrar_Programa_Iniciar.setBackground(new java.awt.Color(250, 205, 195));
        Cerrar_Programa_Iniciar.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        Cerrar_Programa_Iniciar.setText("Salir");
        Cerrar_Programa_Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cerrar_Programa_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cerrar_Programa_IniciarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(180, 171, 168));
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 171, 168));
        jLabel2.setText("Bienvenido");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cerrar_Programa_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86)
                .addComponent(Cerrar_Programa_Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton que realiza la confirmacion de inicio de sesion ademas de verificar todos los datos ingresados por el usuario
     * @param evt 
     */
    private void Verificar_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verificar_DatosActionPerformed
        ClientePersona cliente =new ClientePersona() {};
        
        cliente.setNroCuenta(Integer.parseInt(IngresarNroCuenta.getText().trim()));
        char[] pinCharArray = IngresarPinCuenta.getPassword();
        cliente.setPin(Integer.parseInt(new String(pinCharArray)));
        
        
        String ubicacion_Archivos = "src\\Documentos\\Usuarios\\Usuario";
        
        int datosCorrectos = Funciones.verificarAcceso(cliente, ubicacion_Archivos);
        
        
        if (datosCorrectos!=0){
            
            if (Funciones.verificarTipoCliente(ubicacion_Archivos+datosCorrectos+".txt")==1){
                cliente= Funciones.leerClientePDesdeArchivo(ubicacion_Archivos+datosCorrectos+".txt",datosCorrectos);
                
            } else {
                ClienteEntidad clienteVerd2 = new ClienteEntidad();
                clienteVerd2= Funciones.leerClienteEDesdeArchivo(ubicacion_Archivos+datosCorrectos+".txt",datosCorrectos);
                
            }
            
            
            Interfaz_Pantalla_Principal ventana=new Interfaz_Pantalla_Principal();
            ventana.setVisible(true);
            this.dispose();
            
            IngresarNroCuenta.setText("");
            IngresarPinCuenta.setText("");
        }else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectas, favor ingrese de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Verificar_DatosActionPerformed
    /**
     * Metodo que realiza a finalizacion del programa
     * @param evt 
     */
    private void Cerrar_Programa_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cerrar_Programa_IniciarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Cerrar_Programa_IniciarActionPerformed
    /**
     * Cuadro de texto que almacena los datos del pin de cuenta del usuario
     * @param evt 
     */
    private void IngresarPinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPinCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarPinCuentaActionPerformed
    /**
     * Cuadro de texto que almacena el numero de cuenta del usuario
     * @param evt 
     */
    private void IngresarNroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNroCuentaActionPerformed

    /**
     * Metodo main de la ventana Interfaz_Iniciar_Sesion
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz_Iniciar_Sesion().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar_Programa_Iniciar;
    private javax.swing.JTextField IngresarNroCuenta;
    private javax.swing.JPasswordField IngresarPinCuenta;
    private javax.swing.JLabel Texto_Contrasenha;
    private javax.swing.JButton Verificar_Datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}


}


