/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import Funciones.Funciones;
import clasesFuncionales.Cliente;
import clasesFuncionales.ClienteEntidad;
import clasesFuncionales.ClientePersona;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static pkgfinal.VolverAtras.BotonVolver;




/**
 * Clase de Jframe en donde se realizan los pagos a tarjetas de credito
 * @author lucas
 */
public class Interfaz_Realizar_Pagos_Tarjetas extends javax.swing.JFrame implements VolverAtras {
        /**
         * Atributo que define monto minimo
         */
        private double montoMinimo = 0;
        /**
         * Atributo de MontoFormateado
         */
        private String montoFormateado1 ;
        /**
         * Atributo que define el monto maximo
         */
        private double montoMaximo = 0;
        /**
         * Atributo de monto formateado2
         */
        private String montoFormateado2 ;
        /**
         * Atriburo de limite para los textos
         */
        private int limiteDeNumeros = 7;
        /**
         * Atributo de limite para los textos
         */
        private int limiteDeNumeros2 = 12;
        /**
         * Atriburo de numeros de tarjeta
         */
        protected Long Tarjeta;
        /**
         * Atriburo de monto
         */
        public Long Deuda;
        /**
         * Atriburo del minimo
         */
        protected Long Minimo;
        /**
         * Atributo de terminacion del archivo
         */
        protected int archivo;
        /**
         * Atributo de Posicion tarjeta
         */
        protected int posicionTar;
        /**
         * Instancia del cliente
         */
        private Cliente cliente;
        /**
         * Instancia de la interfaz para evitar duplicados
         */
        private static Interfaz_Realizar_Pagos_Tarjetas instance;
        /**
         * Metodo que devuelve la instancia de la interfaz para evitar duplicados 
         * @return instancia de la ventana
         */
        public static Interfaz_Realizar_Pagos_Tarjetas getInstance() {
            return instance;
        }

    /**
     * Creates new form Realizar_Pagos_Tarjetas
     */
    
    public Interfaz_Realizar_Pagos_Tarjetas() {
        initComponents();
        instance=this;
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        ErrorTarjeta.setVisible(false);
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        montoFormateado1 = String.format("%,.0f", montoMinimo);
        montoFormateado2 = String.format("%,.0f", montoMaximo);
        ValorMinimo.setText(montoFormateado1);
        ValorMaximo.setText(montoFormateado2);
         
          
         
        add(BotonVolver);
        // Cambiar el color del botón usando RGB
        
        Color colorFondo = new Color(245, 203, 195); // para RGB
        BotonVolver.setBackground(colorFondo);
        BotonVolver.setForeground(Color.BLACK); // Cambiar el color del texto

        // Cambiar el tipo de letra del botón
        Font font = new Font("Nirmala UI", Font.PLAIN, 16); 
        BotonVolver.setFont(font);
        
        BotonVolver.setBounds(126, 400, 100, 30);
        BotonVolver.addActionListener(new ActionListener(){  
            public void actionPerformed(ActionEvent e){  
                Interfaz_Pantalla_Principal RealizarPagos =  Interfaz_Pantalla_Principal.getInstance();
        
                RealizarPagos.setVisible(true);
                dispose();
            }  
        }); 
        
        
        //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        // Cancelar Pantalla completa
        setMaximizedBounds(getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ingresar_MontoPagar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonPagotarjetas = new javax.swing.JButton();
        ValorMinimo = new javax.swing.JLabel();
        ValorMaximo = new javax.swing.JLabel();
        IngresarNroTarjeta = new javax.swing.JTextField();
        CargarDatos = new javax.swing.JButton();
        MontoMaximo = new javax.swing.JCheckBox();
        ErrorTarjeta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 102, 104));

        jPanel1.setBackground(new java.awt.Color(114, 145, 147));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel5.setText("Monto M�nimo");

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel3.setText("Monto a Pagar");

        Ingresar_MontoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_MontoPagarActionPerformed(evt);
            }
        });
        Ingresar_MontoPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_MontoPagarKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel6.setText("Monto M�ximo");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel2.setText("Nro. de Tarjeta");

        BotonPagotarjetas.setBackground(new java.awt.Color(245, 205, 195));
        BotonPagotarjetas.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        BotonPagotarjetas.setText("Realizar Pago");
        BotonPagotarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagotarjetasActionPerformed(evt);
            }
        });

        ValorMinimo.setText("Valor");

        ValorMaximo.setText("Valor");

        IngresarNroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNroTarjetaActionPerformed(evt);
            }
        });
        IngresarNroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNroTarjetaKeyTyped(evt);
            }
        });

        CargarDatos.setBackground(new java.awt.Color(245, 205, 195));
        CargarDatos.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        CargarDatos.setText("Cargar Datos");
        CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosActionPerformed(evt);
            }
        });

        MontoMaximo.setText("Monto Maximo");
        MontoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoMaximoActionPerformed(evt);
            }
        });

        ErrorTarjeta.setForeground(new java.awt.Color(255, 51, 51));
        ErrorTarjeta.setText("Tarjeta No encontrada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Ingresar_MontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(BotonPagotarjetas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ValorMinimo))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorMaximo)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IngresarNroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(CargarDatos)))
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ErrorTarjeta)
                            .addComponent(MontoMaximo))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarNroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CargarDatos))
                .addGap(5, 5, 5)
                .addComponent(ErrorTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorMaximo)
                    .addComponent(ValorMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresar_MontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPagotarjetas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MontoMaximo)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pago de Tarjeta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingresar_MontoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_MontoPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_MontoPagarActionPerformed

    private void Ingresar_MontoPagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_MontoPagarKeyTyped
      
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }  
        if (Ingresar_MontoPagar.getText().length() >= limiteDeNumeros   ) {
            evt.consume(); // Rechaza la entrada si se alcanza la longitud máxima
        }
    }//GEN-LAST:event_Ingresar_MontoPagarKeyTyped

    private void IngresarNroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNroTarjetaActionPerformed
        ValorMinimo.setText("");
        ValorMaximo.setText("");
    }//GEN-LAST:event_IngresarNroTarjetaActionPerformed

    private void IngresarNroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNroTarjetaKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }
        if (IngresarNroTarjeta.getText().length() >= limiteDeNumeros2  ) {
            evt.consume(); // Rechaza la entrada si se alcanza la longitud máxima
        }
    }//GEN-LAST:event_IngresarNroTarjetaKeyTyped

    private void CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosActionPerformed
        int ArchivoTarjeta=Funciones.TarjetaAPagar(IngresarNroTarjeta.getText());
        int PosicionTarjeta=00;
        if (ArchivoTarjeta==-1){
            ErrorTarjeta.setVisible(true);
        } else {
            PosicionTarjeta = Funciones.TarjetaAPagarPos(IngresarNroTarjeta.getText(),ArchivoTarjeta);
            ValorMinimo.setText(Funciones.ValorMinimoTarjeta(ArchivoTarjeta,PosicionTarjeta));
            ValorMaximo.setText(Funciones.ValormMaximoTarjeta(ArchivoTarjeta, PosicionTarjeta));
        }
        archivo=ArchivoTarjeta;
        posicionTar=PosicionTarjeta;
    }//GEN-LAST:event_CargarDatosActionPerformed

    private void MontoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoMaximoActionPerformed
        if (MontoMaximo.isSelected()){
            Ingresar_MontoPagar.setEditable(false);
            Ingresar_MontoPagar.setText(ValorMaximo.getText());
        } else {
            Ingresar_MontoPagar.setEditable(true);
        }
    }//GEN-LAST:event_MontoMaximoActionPerformed

    private void BotonPagotarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagotarjetasActionPerformed
        if(IngresarNroTarjeta.getText().isEmpty() || Ingresar_MontoPagar.getText().isEmpty()) {
            int camposVacios = 0;
            StringBuilder mensajeError = new StringBuilder("Error: Uno o más campos están vacíos en los siguientes campos:\n");

            if (IngresarNroTarjeta.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Numero de Tarjeta\n");
            }
            if (Ingresar_MontoPagar.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Monto\n");
            }

            if (camposVacios > 0) {
                // Mostrar solo los campos que no están completos
                JOptionPane.showMessageDialog(this, mensajeError.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        }

        double montoIngresado = 0.0; // Valor por defecto si el campo de monto está vacío
        try {
            montoIngresado = Double.parseDouble(Ingresar_MontoPagar.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese un monto válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (montoIngresado < montoMinimo) {
            JOptionPane.showMessageDialog(this, "Error: El monto ingresado es menor al requerido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (IngresarNroTarjeta.getText().length() != limiteDeNumeros2) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese un número de tarjeta válido con 16 dígitos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Interfaz_Validacion confirmar = new Interfaz_Validacion(4);
        confirmar.setVisible(true);
    }//GEN-LAST:event_BotonPagotarjetasActionPerformed
    /**
     * Metodo que realiza el pago de las tarjetas
     */
    public void Realizar_Pago(){
        
        Long monto = Long.parseLong(Ingresar_MontoPagar.getText());
        Long montoTotal = cliente.getFondos()-monto;

        String LineaSobre1=String.format("Fondos: %-20d", montoTotal);

        /*
        Disminuimos el fondo ya que estamos realizando un pago
        */
        try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\Usuarios\\Usuario"+cliente.getArchivo()+".txt" , "rw")) {
            long posicion=0;
            int aux=1,lineaSob=12;        //En los archivos txt en la linea 11 esta el dato a sobreescribir
            String linea;
            while ((linea = file.readLine()) != null) {
                if (aux==lineaSob) {
                    posicion=file.getFilePointer();
                    break;
                }
                aux++;
            }

            file.seek(posicion);
            file.writeBytes(LineaSobre1);
            file.writeBytes(System.lineSeparator());

        } catch (IOException e) {
            e.printStackTrace();
        }
        /*
        Disminuimos la deuda que posee esa persona en el servicio dado
        */

        long deuda=Long.parseLong(ValorMaximo.getText().trim());

        montoTotal= deuda-monto;
        String LineaSobre2=String.format("%-20d", montoTotal); ;

        try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\TarjetasRegistradas\\Tarjetas"+archivo+".txt" , "rw")) {
            long posicion=0;
            int aux=1,lineaSob=8+posicionTar;        //En los archivos txt en la linea 11 esta el dato a sobreescribir
            String linea;
            while ((linea = file.readLine()) != null) {
                if (aux==lineaSob) {
                    posicion=file.getFilePointer();
                    break;
                }
                aux++;
            }

            file.seek(posicion);
            file.writeBytes(LineaSobre2);
            file.writeBytes(System.lineSeparator());

        } catch (IOException e) {
            e.printStackTrace();
        }
        
        Agregar_Pago_Historial();
        JOptionPane.showMessageDialog(this, "Pago de tarjeta realizado con exito!!", "Pago Exitosa", JOptionPane.INFORMATION_MESSAGE);
        Interfaz_Pantalla_Principal principal = Interfaz_Pantalla_Principal.getInstance();
        principal.setVisible(true);
        Detalles_Operacion detalles = new Detalles_Operacion(4,monto,IngresarNroTarjeta.getText());
        detalles.setVisible(true);
        dispose();

    }
    
    private void Agregar_Pago_Historial(){
        String ubicacion_Archivos="src\\Documentos\\Historiales\\Historial";
        int iteracion=0;
        while (true){
            iteracion++;
            String Terminacion=iteracion+".txt";
            try(RandomAccessFile file = new RandomAccessFile(ubicacion_Archivos+Terminacion, "rw")){
                
                String linea=linea=file.readLine();
                
                Integer NroCuenta=Integer.parseInt(linea.substring("NroCuenta: ".length()).trim());

                if (NroCuenta.equals(cliente.getNroCuenta())){
                    
                    while ((linea=file.readLine())!=null);
                    LocalDate fechaHora = LocalDate.now();
                    String LineaSobre1=String.format("|%-10s|%-30s|%-20d|%-12s|\n", fechaHora.toString(),"Pago Tarjeta "+IngresarNroTarjeta.getText() ,Long.parseLong(Ingresar_MontoPagar.getText()),"Negativo");
                    file.writeBytes(LineaSobre1);
                    String LineaDos="|----------|------------------------------|--------------------|------------|\n";
                    file.writeBytes(LineaDos);
                    break;
                }
                
            } catch(Exception e){
                System.out.println("Error");
                break;
            }
        }
    }
    
    /**
     * Metodo main de la ventana Interfaz_Realizar_Pagos_Tarjetas
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPagotarjetas;
    private javax.swing.JButton CargarDatos;
    private javax.swing.JLabel ErrorTarjeta;
    private javax.swing.JTextField IngresarNroTarjeta;
    private javax.swing.JTextField Ingresar_MontoPagar;
    private javax.swing.JCheckBox MontoMaximo;
    private javax.swing.JLabel ValorMaximo;
    private javax.swing.JLabel ValorMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}


}
