/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import clasesFuncionales.ClientePersona;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static pkgfinal.VolverAtras.BotonVolver;
import Funciones.*;
import clasesFuncionales.Cliente;
import clasesFuncionales.ClienteEntidad;
import clasesFuncionales.Deposito;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
/**
 * Objeto interfaz en donde se realiza los depositos imaginarios
 * @author lucas
 */
public class Interfaz_Realizar_Deposito extends javax.swing.JFrame  implements VolverAtras {
    
    FondoPanel fondo=new FondoPanel();
    /**
     * Atributo que define el limite de CI
     */
    private int limiteDeCi=7;
    /**
     * Atributo que valida una confirmacion
     */
    protected boolean confirmacion; 
    /**
     * Instancia del cliente actual 
     */
    protected Cliente cliente;
    /**
     * Atributo de deposito para usar en el programa
     */
    public Deposito CuentaDeposito;
    /**
     * Instancia de la ventana actual para evitar duplicados
     */
    private static Interfaz_Realizar_Deposito instance;
    /**
     * Metodo que devuelve la instancia de la ventana para evitar duplicados
     * @return Instancia
     */
    public static Interfaz_Realizar_Deposito getInstance() {
        return instance;
    }
    /**
     * Creates new form RealizarDeposito
     */
    public Interfaz_Realizar_Deposito() {
        initComponents();
        instance = this;
        
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        
        CuentaDeposito = new Deposito();
        
        
        add(BotonVolver);
        // Cambiar el color del botÃ³n usando RGB
        Color colorFondo = new Color(245, 203, 195); // para RGB
        BotonVolver.setBackground(colorFondo);
        BotonVolver.setForeground(Color.BLACK); // Cambiar el color del texto

        // Cambiar el tipo de letra del botÃ³n
        Font font = new Font("Nirmala UI", Font.PLAIN, 16); 
        BotonVolver.setFont(font);
        
        
        BotonVolver.setBounds(80, 440, 100, 30);
        BotonVolver.addActionListener(new ActionListener(){  
            public void actionPerformed(ActionEvent e){  
                Interfaz_Pantalla_Principal PantallaPrincipal = Interfaz_Pantalla_Principal.getInstance();
                
                PantallaPrincipal.setVisible(true);
                dispose();
            }  
        });
        
        //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Ingresar_MontoDeposito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Ingresar_NroDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IngresarNombreTitular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ingresar_NroCuenta = new javax.swing.JTextField();
        BotonDepósito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 102, 104));

        jPanel1.setBackground(new java.awt.Color(114, 145, 147));

        Ingresar_MontoDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_MontoDepositoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel2.setText("Ingrese el monto a Depositar");

        Ingresar_NroDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_NroDocumentoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel4.setText("Nro. de Documento");

        IngresarNombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarNombreTitularActionPerformed(evt);
            }
        });
        IngresarNombreTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarNombreTitularKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel3.setText("Nombre del Titular");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel5.setText("Número de Cuenta");

        Ingresar_NroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ingresar_NroCuentaKeyTyped(evt);
            }
        });

        BotonDepósito.setBackground(new java.awt.Color(245, 203, 195));
        BotonDepósito.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        BotonDepósito.setText("Confirmar Deposito");
        BotonDepósito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDepósitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ingresar_MontoDeposito)
                    .addComponent(IngresarNombreTitular)
                    .addComponent(Ingresar_NroDocumento))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(Ingresar_NroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(BotonDepósito)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarNombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ingresar_NroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ingresar_NroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresar_MontoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDepósito))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(245, 203, 195));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 203, 195));
        jLabel1.setText("Depósito");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarNombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarNombreTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarNombreTitularActionPerformed
    /**
     * Cuadro de texto que almacena el nombre del titular ademas de rechazar los valores numericos
     * @param evt 
     */
    private void IngresarNombreTitularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarNombreTitularKeyTyped
       char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
             evt.consume();  // Rechaza la entrada que sea un nÃºmero
        }
    }//GEN-LAST:event_IngresarNombreTitularKeyTyped
    /**
     * Cuadro de texto que almacena el documento del titular y rechaza valores que no sean numericos
     * @param evt 
     */
    private void Ingresar_NroDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_NroDocumentoKeyTyped
         char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un nÃºmero, retroceso o suprimir
        }
        
         if (Ingresar_NroDocumento.getText().length() >= limiteDeCi ) {
            evt.consume(); // Rechaza la entrada si se alcanza la longitud mÃ¡xima
        }
    }//GEN-LAST:event_Ingresar_NroDocumentoKeyTyped
    /**
     * Cuadro de texto que almacena el monto a ser depositado
     * @param evt 
     */
    private void Ingresar_MontoDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_MontoDepositoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un nÃºmero, retroceso o suprimir
        }
    }//GEN-LAST:event_Ingresar_MontoDepositoKeyTyped
    /**
     * Cuadro de texto en donde se almacena el nro de cuenta del usuario a ser depositado
     * @param evt 
     */
    private void Ingresar_NroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ingresar_NroCuentaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un nÃºmero, retroceso o suprimir
        }
    }//GEN-LAST:event_Ingresar_NroCuentaKeyTyped
    /**
     * Boton que realiza la confirmacion del deposito ademas de las confirmaciones necesarias
     * @param evt 
     */
    private void BotonDepósitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDepósitoActionPerformed
        if (Ingresar_MontoDeposito.getText().isEmpty() || IngresarNombreTitular.getText().isEmpty() || 
                Ingresar_NroDocumento.getText().isEmpty() || Ingresar_NroCuenta.getText().isEmpty()    ) {
             int camposVacios = 0;
            StringBuilder mensajeError = new StringBuilder("Error: Uno o mÃ¡s campos estÃ¡n vacÃ­os en los siguientes campos:\n");
            
            if (Ingresar_MontoDeposito.getText().isEmpty()){
                camposVacios++;
                mensajeError.append("- Monto\n");
            }
            
            if(IngresarNombreTitular.getText().isEmpty()){
                camposVacios++;
                mensajeError.append("- Nombre\n");
            } 
            
            if (Ingresar_NroDocumento.getText().isEmpty()){
                camposVacios++;
                mensajeError.append("- Cedula\n");
            }
            
            if(Ingresar_NroCuenta.getText().isEmpty()){
                camposVacios++;
                mensajeError.append("- Numero de Cuenta");
            }
            
             if (camposVacios > 0) {
                // Mostrar solo los campos que no estÃ¡n completos
                JOptionPane.showMessageDialog(this, mensajeError.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        
        }
        
        if (!Funciones.ExistenciaCuenta(Ingresar_NroCuenta.getText())){
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no esta en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        CuentaDeposito.setId(Integer.parseInt(Ingresar_NroCuenta.getText().trim() ) );
        CuentaDeposito.setMonto(Long.parseLong(Ingresar_MontoDeposito.getText().trim()));
        Interfaz_Validacion confirmar=new Interfaz_Validacion(1);
        confirmar.setVisible(true);

    }//GEN-LAST:event_BotonDepósitoActionPerformed
    /**
     * Metodo que realiza el depostio en otra cuienta ya existente, si no existe dicha cuenta salta un error
     */
    public void RealizarDeposito(){
        
        int NroCuenta = Integer.parseInt(Ingresar_NroCuenta.getText().trim());
        
        int cuenta = Funciones.verificarExistenciaCuenta(CuentaDeposito.getId(), "src\\Documentos\\Usuarios\\Usuario");
        if (cuenta!=0){
            ClientePersona cliente2 = new ClientePersona();
            cliente2 = Funciones.leerClientePDesdeArchivo("src\\Documentos\\Usuarios\\Usuario"+cuenta+".txt" ,cuenta );
            
            long monto = Long.parseLong(Ingresar_MontoDeposito.getText().trim());
            long montoTotal = cliente2.getFondos()+monto;
            
            String LineaSobre=String.format("Fondos: %-20d", montoTotal);
            
            try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\Usuarios\\Usuario"+cuenta+".txt" , "rw")) {
                long posicion=0;
                int aux=1,lineaSob=12;        //En los archivos txt en la linea 11 esta el dato a sobreescribir
                String linea;
                while ((linea = file.readLine()) != null) {
                    if (aux==lineaSob) {
                        posicion=file.getFilePointer();
                        break;
                    }
                    aux++;
                }
                
                file.seek(posicion);
                file.writeBytes(LineaSobre);
                file.writeBytes(System.lineSeparator());
                
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,"La cuenta que desea depositar no existe dentro del sistema", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Agregar_Deposito_Historial();
            JOptionPane.showMessageDialog(this, "Deposito realizado con exito!!", "Deposito", JOptionPane.INFORMATION_MESSAGE);
            
            Interfaz_Pantalla_Principal principal = Interfaz_Pantalla_Principal.getInstance();
            principal.setVisible(true);
            
            Detalles_Operacion detalles = new Detalles_Operacion(1,monto,"");
            detalles.setVisible(true);
            dispose();
            
        }
        
    }
    
    private void Agregar_Deposito_Historial(){
        String ubicacion_Archivos="src\\Documentos\\Historiales\\Historial";
        int iteracion=0;
        while (true){
            iteracion++;
            String Terminacion=iteracion+".txt";
            try(RandomAccessFile file = new RandomAccessFile(ubicacion_Archivos+Terminacion, "rw")){
                
                String linea=linea=file.readLine();
                
                Integer NroCuenta=Integer.parseInt(linea.substring("NroCuenta: ".length()).trim());

                if (NroCuenta.equals(cliente.getNroCuenta())){
                    
                    while ((linea=file.readLine())!=null);
                    LocalDate fechaHora = LocalDate.now();
                    String LineaSobre1=String.format("|%-10s|%-30s|%-20d|%-12s|\n", fechaHora.toString(),"Deposito",Long.parseLong(Ingresar_MontoDeposito.getText()),"Positivo");
                    file.writeBytes(LineaSobre1);
                    String LineaDos="|----------|------------------------------|--------------------|------------|\n";
                    file.writeBytes(LineaDos);
                    break;
                }
                
            } catch(Exception e){
                System.out.println("Error");
                break;
            }
        }
    }
    /**
     * Metodo main de la ventana Realizar_Deposito
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDepósito;
    private javax.swing.JTextField IngresarNombreTitular;
    private javax.swing.JTextField Ingresar_MontoDeposito;
    private javax.swing.JTextField Ingresar_NroCuenta;
    private javax.swing.JTextField Ingresar_NroDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}

}
