/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import Funciones.Funciones;
import clasesFuncionales.Cliente;
import clasesFuncionales.ClienteEntidad;
import clasesFuncionales.ClientePersona;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static pkgfinal.VolverAtras.BotonVolver;

/**
 * Clase de Jframe en donde se realizan los pagos a entidades
 * @author lucas
 */
public class Interfaz_Realizar_Pagos_Entidad extends javax.swing.JFrame  implements VolverAtras {
    
    FondoPanel fondo= new FondoPanel();
    /**
     * Instancia del cliente actual
     */
    protected Cliente cliente;
    /**
     * Array de las emresas
     */
    protected ArrayList<String> Empresas;
    /**
     * Array de las cuentas
     */
    protected ArrayList<Integer> Cuentas;
    /**
     * Array de las deudas
     */
    protected ArrayList<Long> Deudas;
    /**
     * Instancia de la ventana Interfaz_Realizar_Pagos_Entidad
     */
    private static Interfaz_Realizar_Pagos_Entidad instance;
    /**
     * Metodo que devuelve la instancia de la ventana para evitar duplicados
     * @return Instancia de la ventana
     */
    public static Interfaz_Realizar_Pagos_Entidad getInstance() {
        return instance;
    }
    /**
     * Creates new form Realizar_Pagos_Entidad
     */
    public Interfaz_Realizar_Pagos_Entidad() {
        initComponents();
        instance=this;
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        
        String ubicacion_Archivos = "src\\Documentos\\Usuarios\\Usuario";
        Empresas=Funciones.EmpresasServicio();
        
        for (String empresa : Empresas){
            ComboDeEntidad.addItem(empresa);
        }
        
        add(BotonVolver);
        
        // Cambiar el color del botón usando RGB
        Color colorFondo = new Color(245, 203, 195); // para RGB
        BotonVolver.setBackground(colorFondo);
        BotonVolver.setForeground(Color.BLACK); // Cambiar el color del texto

        // Cambiar el tipo de letra del botón
        Font font = new Font("Nirmala UI", Font.PLAIN, 16); 
        BotonVolver.setFont(font);
        BotonVolver.setBounds(142, 422, 100, 30);
        BotonVolver.addActionListener(new ActionListener(){  
            public void actionPerformed(ActionEvent e){  
                Interfaz_Pantalla_Principal PantallaPagos = Interfaz_Pantalla_Principal.getInstance();
        
                PantallaPagos.setVisible(true);
                dispose();
            }  
        }); 
        
        
        //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        // Cancelar Pantalla completa
        setMaximizedBounds(getBounds());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new FondoPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotonRealizarPagos = new javax.swing.JButton();
        ComboDeEntidad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoNroCuenta = new javax.swing.JTextField();
        ComboDeServicio = new javax.swing.JComboBox<>();
        NombreServicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DeudaTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MontoAPagar = new javax.swing.JTextField();
        PagarTotal = new javax.swing.JCheckBox();
        CargarCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(94, 102, 104));

        jPanel1.setBackground(new java.awt.Color(114, 145, 147));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jLabel2.setText("Selecionar Entidad");

        BotonRealizarPagos.setBackground(new java.awt.Color(245, 205, 195));
        BotonRealizarPagos.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        BotonRealizarPagos.setText("Realizar Pago");
        BotonRealizarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRealizarPagosActionPerformed(evt);
            }
        });

        ComboDeEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDeEntidadActionPerformed(evt);
            }
        });

        jLabel8.setText("Seleccionar Servicio");

        jLabel7.setText("Nro. de Cuenta a pagar");

        CampoNroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNroCuentaActionPerformed(evt);
            }
        });

        ComboDeServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDeServicioActionPerformed(evt);
            }
        });

        NombreServicio.setEditable(false);
        NombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreServicioActionPerformed(evt);
            }
        });
        NombreServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreServicioKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre del servicio a pagar");

        jLabel5.setText("Monto de deuda");

        DeudaTotal.setEditable(false);
        DeudaTotal.setToolTipText("");

        jLabel6.setText("Monto a Pagar");

        PagarTotal.setText("Pagar Total");
        PagarTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarTotalActionPerformed(evt);
            }
        });

        CargarCuenta.setBackground(new java.awt.Color(245, 205, 195));
        CargarCuenta.setText("Cargar Cuenta");
        CargarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(288, Short.MAX_VALUE)
                        .addComponent(BotonRealizarPagos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(ComboDeEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CampoNroCuenta)
                                            .addComponent(ComboDeServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CargarCuenta)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PagarTotal)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(NombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(DeudaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(MontoAPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboDeEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboDeServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeudaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PagarTotal)
                    .addComponent(CargarCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BotonRealizarPagos)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel1.setText("Pago de Servicios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRealizarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRealizarPagosActionPerformed
        
        if(NombreServicio.getText().isEmpty() || DeudaTotal.getText().isEmpty()) {
            int camposVacios = 0;
            StringBuilder mensajeError = new StringBuilder("Error: Uno o más campos están vacíos en los siguientes campos:\n");

            if (NombreServicio.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Identificador de Entidad \n");
            }
            if (DeudaTotal.getText().isEmpty()) {
                camposVacios++;
                mensajeError.append("- Monto\n");
            }

            if (camposVacios > 0) {
                // Mostrar solo los campos que no están completos
                JOptionPane.showMessageDialog(this, mensajeError.toString(), "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        }
        
        long fondos=cliente.getFondos();
        long MontoPagar=Long.parseLong(MontoAPagar.getText());
        long DeudaTTotal=Long.parseLong(DeudaTotal.getText());
        if (MontoPagar>fondos){
            JOptionPane.showMessageDialog(this, "Fondos insuficientes", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (MontoPagar>DeudaTTotal){
            JOptionPane.showMessageDialog(this, "No puede pagar mas de lo que debe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Interfaz_Validacion ventana= new Interfaz_Validacion(3);
        ventana.setVisible(true);
        
        
    }//GEN-LAST:event_BotonRealizarPagosActionPerformed
    /**
     * Metodo que realiza el pago
     */
    public void Realizar_Pago(){
        int NroCuenta = Integer.parseInt(CampoNroCuenta.getText().trim());
        
        if (true){
            
            Long monto = Long.parseLong(MontoAPagar.getText().trim());
            Long montoTotal = cliente.getFondos()-monto;
           
            String LineaSobre1=String.format("Fondos: %-20d", montoTotal);
            
            /*
            Disminuimos el fondo ya que estamos realizando un pago
            */
            try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\Usuarios\\Usuario"+cliente.getArchivo()+".txt" , "rw")) {
                long posicion=0;
                int aux=1,lineaSob=12;        //En los archivos txt en la linea 12 esta el dato a sobreescribir
                String linea;
                while ((linea = file.readLine()) != null) {
                    if (aux==lineaSob) {
                        posicion=file.getFilePointer();
                        break;
                    }
                    aux++;
                }
                
                file.seek(posicion);
                file.writeBytes(LineaSobre1);
                file.writeBytes(System.lineSeparator());
                
            } catch (IOException e) {
                e.printStackTrace();
            }
            /*
            Disminuimos la deuda que posee esa persona en el servicio dado
            */
            long deuda=Long.parseLong(DeudaTotal.getText().trim());
            
            montoTotal= deuda-monto;
            String LineaSobre2=String.format("%-20d", montoTotal); ;
            
            int archivo = Funciones.VerificarArchivoServicio(ComboDeEntidad.getSelectedItem().toString(),ComboDeServicio.getSelectedItem().toString());
            

            try (RandomAccessFile file = new RandomAccessFile("src\\Documentos\\ServiciosRegistrados\\Servicio"+archivo+".txt" , "rw")) {
                long posicion=0;
                int aux=1,lineaSob=12+Cuentas.indexOf(cliente.getNroCuenta());        //En los archivos txt en la linea 11 esta el dato a sobreescribir
                String linea;
                while ((linea = file.readLine()) != null) {
                    if (aux==lineaSob) {
                        posicion=file.getFilePointer();
                        break;
                    }
                    aux++;
                }
                
                file.seek(posicion);
                file.writeBytes(LineaSobre2);
                file.writeBytes(System.lineSeparator());
                
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            Agregar_Pago_Historial();
            JOptionPane.showMessageDialog(this, "Pago realizado con exito!!", "Pago Exitoso", JOptionPane.INFORMATION_MESSAGE);
            Interfaz_Pantalla_Principal principal = Interfaz_Pantalla_Principal.getInstance();
            principal.setVisible(true);
            Detalles_Operacion detalles = new Detalles_Operacion(3,monto,ComboDeEntidad.getSelectedItem().toString()+"-"+ComboDeServicio.getSelectedItem());
            detalles.setVisible(true);
            dispose();
            
        }
    }

    private void Agregar_Pago_Historial(){
        String ubicacion_Archivos="src\\Documentos\\Historiales\\Historial";
        int iteracion=0;
        while (true){
            iteracion++;
            String Terminacion=iteracion+".txt";
            try(RandomAccessFile file = new RandomAccessFile(ubicacion_Archivos+Terminacion, "rw")){
                
                String linea=linea=file.readLine();
                
                Integer NroCuenta=Integer.parseInt(linea.substring("NroCuenta: ".length()).trim());

                if (NroCuenta.equals(cliente.getNroCuenta())){
                    
                    while ((linea=file.readLine())!=null);
                    LocalDate fechaHora = LocalDate.now();
                    String LineaSobre1=String.format("|%-10s|%-30s|%-20d|%-12s|\n", fechaHora.toString(),"Pago Entidad "+ComboDeEntidad.getSelectedItem().toString() ,Long.parseLong(MontoAPagar.getText()),"Negativo");
                    file.writeBytes(LineaSobre1);
                    String LineaDos="|----------|------------------------------|--------------------|------------|\n";
                    file.writeBytes(LineaDos);
                    break;
                }
                
            } catch(Exception e){
                System.out.println("Error");
                break;
            }
        }
    }
    
    private void ComboDeEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDeEntidadActionPerformed
        ComboDeServicio.removeAllItems();
        String itemSelec = ComboDeEntidad.getSelectedItem().toString();
        ArrayList<String> Servicios = Funciones.EmpresasServicioDeuda(itemSelec);
        for (String Servicio : Servicios){
            ComboDeServicio.addItem(Servicio);
        }
        NombreServicio.setText("");
        DeudaTotal.setText("");
    }//GEN-LAST:event_ComboDeEntidadActionPerformed

    private void CampoNroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNroCuentaActionPerformed

    private void ComboDeServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDeServicioActionPerformed
        NombreServicio.setText("");
        DeudaTotal.setText("");
    }//GEN-LAST:event_ComboDeServicioActionPerformed

    private void NombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreServicioActionPerformed

    private void NombreServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreServicioKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }

    }//GEN-LAST:event_NombreServicioKeyTyped

    private void PagarTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarTotalActionPerformed
        if (PagarTotal.isSelected()){
            MontoAPagar.setEditable(false);
            MontoAPagar.setText(DeudaTotal.getText());
        } else {
            MontoAPagar.setEditable(true);
        }

    }//GEN-LAST:event_PagarTotalActionPerformed

    private void CargarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarCuentaActionPerformed

        String Servicio=ComboDeServicio.getSelectedItem().toString();
        Cuentas = Funciones.EmpresasServicioDeudaCuenta(Servicio);
        Deudas = Funciones.EmpresasServicioDeudaValor(ComboDeServicio.getSelectedItem().toString());

        if (!Cuentas.contains(cliente.getNroCuenta())){
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no posee deuda1", "Sin Deuda", JOptionPane.OK_OPTION);
            return;
        }

        int PosicionDeuda = Cuentas.indexOf(cliente.getNroCuenta());

        if (Deudas.get(PosicionDeuda)==0){
            JOptionPane.showMessageDialog(this, "La cuenta ingresada no posee deuda2", "Sin Deuda", JOptionPane.OK_OPTION);
            return;
        }

        NombreServicio.setText(ComboDeServicio.getSelectedItem().toString());
        DeudaTotal.setText(Deudas.get(PosicionDeuda).toString());

    }//GEN-LAST:event_CargarCuentaActionPerformed

    /**
     * Metodo main de Interfaz_Realizar_Pagos_Entidad
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Realizar_Pagos_Entidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Realizar_Pagos_Entidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRealizarPagos;
    private javax.swing.JTextField CampoNroCuenta;
    private javax.swing.JButton CargarCuenta;
    private javax.swing.JComboBox<String> ComboDeEntidad;
    private javax.swing.JComboBox<String> ComboDeServicio;
    private javax.swing.JTextField DeudaTotal;
    private javax.swing.JTextField MontoAPagar;
    private javax.swing.JTextField NombreServicio;
    private javax.swing.JCheckBox PagarTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel {
    private Image imagen;

    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/Fpuna.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
}
}
