/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.awt.event.KeyEvent;
import clasesFuncionales.Cliente;
import clasesFuncionales.ClientePersona;
import clasesFuncionales.ClienteEntidad;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import static pkgfinal.VolverAtras.BotonVolver;

/**
 * Ventana de Jframe que funciona para validar el pin del usuario
 * @author lucas
 */
public class Interfaz_Validacion extends javax.swing.JFrame {
    /**
     * Atributo que limita el pin
     */
    private int limiteDePin=4;
    /**
     * Atributo que define de que ventana viene
     */
    private int proviene;
    /**
     * Atributo de la instancia cliente actual
     */
    public Cliente cliente;
    /**
     * Creates new form Validacion
     * @param numero numero que define de que ventana viene
     */
    public Interfaz_Validacion(int numero) {
        initComponents();
        proviene = numero;
        
        ClientePersona clientePA= ClientePersona.getInstance();
        ClienteEntidad clienteEA= ClienteEntidad.getInstance();
        
        if (clientePA!=null){
            cliente = clientePA;
        } else{
            cliente = clienteEA;
        }
        //Para que el Boton aparezca encima de todo 
        JLayeredPane layeredPane = getLayeredPane();
        layeredPane.add(BotonVolver, JLayeredPane.PALETTE_LAYER);
        // Para Abrir las ventana en el centro
        setLocationRelativeTo(null);
        // Cancelar Pantalla completa
        setMaximizedBounds(getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        IngresarPinTransaccion = new javax.swing.JTextField();
        BotonConfirmar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 102, 104));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese su pin de transacci�n");

        jPanel2.setBackground(new java.awt.Color(114, 145, 147));

        IngresarPinTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPinTransaccionActionPerformed(evt);
            }
        });
        IngresarPinTransaccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IngresarPinTransaccionKeyTyped(evt);
            }
        });

        BotonConfirmar.setBackground(new java.awt.Color(245, 205, 195));
        BotonConfirmar.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        BotonCancelar.setBackground(new java.awt.Color(245, 205, 195));
        BotonCancelar.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonConfirmar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(IngresarPinTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(IngresarPinTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonConfirmar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo cancelar que cierra la ventana emergente
     * @param evt 
     */
    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void IngresarPinTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPinTransaccionActionPerformed
       
    }//GEN-LAST:event_IngresarPinTransaccionActionPerformed
    /**
     * Cuadro de texto en donde se ingresa el pin del usuario
     * @param evt 
     */
    private void IngresarPinTransaccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IngresarPinTransaccionKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();  // Rechaza la entrada que no sea un número, retroceso o suprimir
        }
        
         if (IngresarPinTransaccion.getText().length() >= limiteDePin ) {
            evt.consume(); // Rechaza la entrada si se alcanza la longitud máxima
        }
    }//GEN-LAST:event_IngresarPinTransaccionKeyTyped
    /**
     * Boton de confirmacion de validacion de pin que llama a diferentes operadores segun sea la operacion dada
     * @param evt 
     */
    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
         int pinTransferencia = cliente.getPinTransf();
        
        int pinIngresado = Integer.parseInt(IngresarPinTransaccion.getText().trim());
        
        /*
        El valor ingresado en el valor proviene indica que ventana es la que tiene que volver a abrir una vez realice las operaciones
        1- Deposito
        2- Transferencia
        3- Pago de un servicio de entidad
        4- Pago de una tarjeta de credito
        */
        if (pinTransferencia == pinIngresado ){
             
            switch (proviene){
                case 1:
                    Interfaz_Realizar_Deposito Realizar_Deposito = Interfaz_Realizar_Deposito.getInstance();
                    Realizar_Deposito.RealizarDeposito();
                    this.dispose();
                    break;
                case 2:
                    Interfaz_Transferencia Transferencia= Interfaz_Transferencia.getInstance();
                    Transferencia.Realizar_Transferencia();
                    this.dispose();
                    break;
                case 3:
                    Interfaz_Realizar_Pagos_Entidad Pago_Entidad = Interfaz_Realizar_Pagos_Entidad.getInstance();
                    Pago_Entidad.Realizar_Pago();
                    this.dispose();
                    break;
                case 4:
                    Interfaz_Realizar_Pagos_Tarjetas Pago_tarjeta = Interfaz_Realizar_Pagos_Tarjetas.getInstance();
                    Pago_tarjeta.Realizar_Pago();
                    this.dispose();
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pin de Transferencia incorrecto, inténtelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    /**
     * Metodo main de la ventana Interfaz_Validacion
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JTextField IngresarPinTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
